name: CloverOpProtector
version: 1.3
author: fread
main: com.fread.cloverOpProtector.AdminProtectionPlugin
api-version: 1.16
commands:
  pass:
    description: Log in as admin.
    aliases: [adminlogin, protect, pro, log, l]